--- #YAML:1.0
name:                Dicop-Base
version:             3.05
abstract:            basics for a Dicop HTTP server/client
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36_01
distribution_type:   module
requires:     
    Digest::MD5:                   2.09
    File::Spec:                    0.82
    HTML::Tagset:                  3.03
    HTTP::Request:                 1.24
    Mail::Sendmail:                0.77
    Math::BigInt:                  1.88
    Math::String:                  1.28
    Net::Server:                   0.97
    Test::More:                    0.47
    Time::HiRes:                   1.2
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - BSI
